<option value="1" <?php gv($_GET['id'],2); ?>>acc sec</option>
<option value="2">	view all	</option>
<option value="3">	active</option>
<option value="4">	add</option>
<option value="5">	type</option>
<option value="6">locatio sec</option>
<option value="7">	all</option>
<option value="8">	post</option>
<option value="9">	area</option>
<option value="10">	village </option>
<option value="11">	street</option>
<option value="12">other</option>
<option value="13">	all</option>
<option value="14">	tap</option>
<option value="15">	gd</option>
<option value="16">	bill</option>
<option value="17">users</option>
<option value="18">	admin</option>
<option value="19">	cus</option>
<option value="20">report</option>
<option value="21">	incom</option>
<option value="22">	expenses</option>
<option value="23">	card</option>
<option value="24">income</option>
<option value="25">	inc</option>
<option value="26">	cat</option>
<option value="27">ex</option>
<option value="28">	ex</option>
<option value="29">	cat</option>
<option value="30">paym</option>
<option value="31">	pay</option>
<option value="32">	cat</option>
<option value="33">bin</option>
<option value="34">	ac </option>
<option value="35">	acc ty</option>
<option value="36">	admi</option>
<option value="37">	cus</option>
<option value="38">	inc cat</option>
<option value="39">	ex cat</option>
<option value="40">settig</option>
<option value="41">	moth pln</option>
<option value="42">	pay types</option>
<option value="43">	ad priv</option>
<option value="44">	view pr</option>
<option value="45">	other</option>
